version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    env_file:
      - ./.env
    depends_on:
      - redis
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - cartoonverse-temp:/tmp/cartoonverse

  worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    env_file:
      - ./.env
    depends_on:
      - redis
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    restart: unless-stopped
    volumes:
      - cartoonverse-temp:/tmp/cartoonverse

volumes:
  cartoonverse-temp:
    driver: local
